version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu-latest
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Run Tests and Coverage
          command: |
            coverage run -m unittest discover
            coverage report

      - run:
          name: Static Analysis
          command: pylint --fail-under=9.5 restapi.py system_stats.py

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: coverage

      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/restapi:latest .

      - run:
          name: Push Docker Image to DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/restapi:latest
